### ISSUE TITLE
improvement: mark non graded questions as zero

### ISSUE THREAD

**Issue by koenr** [StudiUM/moodle-quiz_markspersection#1]
There is a different behaviour in the marks per section / grades report / manual grading report of the quiz. 
When using essay questions, blank responses are not offered for manual grading. The grades report shows a dash, but counts a 0 for the marks - there is a total for the quiz. The marks per section report shows Not yet graded. 

This is not consistent with how the grades report treats unmarked blank questions.
It is also quite cumbersome to fix for a teacher, because you can't filter those blank questions to grade them with a zero: they don't show up in the manual grading page.

I had a teacher reporting an "Exception - Unsupported operand types: string + float" error on showing the marks per section report with non graded blank questions, but up to now I didn't manage to reproduce that.

Steps to reproduce.

- Create a quiz
- Add two questions, each in a different section - at least one question should be an essay question
- As a student: make an attempt, leave the essay question blank
- As a teacher: do manual grading - the blank essay question won't be offered to grade
- As a teacher: look at the grades report - the quiz has grades
- As a teacher: look at the marks per section report - the report says "Not yet graded" for the section with the essay question

Expected behaviour: the marks per section reports counts the blank answered question as a zero and shows the grades for the section.

**Comment by koenr** [comment]
The teacher showed me the "Exception - Unsupported operand types: string + float" - problem: it shows if you look at a group, rather then looking at all participants on the Mark per sections report page. I wonder if I should report this as a separate issue.

**Comment by levemar** [comment]
Hi @koenr!

Thanks for reporting these issues. I was able to reproduce the first one (essay question). For the second, I did not have the exact same error, but I did get a warning with a quiz with separated groups.

I put them in our backlog, but if you (or somebody else) can provide a pull request, a patch or something like that, it will help us to address these issues faster.

Thanks!
Marie-Eve

**Comment by binhdv1983** [comment]
Hi @koenr, @levemar,
For the second issue, the error message will be shown with php8.0, and with php7.4, it will be a warning message.

**Comment by leblangi** [comment]
This is now fixed in the latest master branch.
